//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestServerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Customer_Sale = new HashSet<Customer_Sale>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public Nullable<int> Quantity_Available { get; set; }
        public Nullable<int> Quantity_Sold { get; set; }
        public Nullable<int> Unit_Price { get; set; }
        public Nullable<int> Selling_Price { get; set; }
        public string Des { get; set; }
        public Nullable<System.DateTime> Date_Updated { get; set; }
        public string Unique_Barcode { get; set; }
    
        public virtual ICollection<Customer_Sale> Customer_Sale { get; set; }
    }
}
